#include<stdio.h>
int main(){
    printf("#########################################\n");
    printf("#             BEM VINDA                 #\n");
    printf("#         _           _   _             #\n");
    printf("#        | |         | | (_)            #\n");
    printf("#        | |  _   _  | |  _    ____     #\n");
    printf("#    _   | | | | | | | | | |  / _  |    #\n");
    printf("#   | |__| | | |_| | | | | | | (_| |    #\n");
    printf("#   |_____/  |_____| |_| |_| |_____|    #\n");
    printf("#                                       #\n");
    printf("#      AS NOTAS A SEGUIR APARECERAO     #\n");
    printf("#      ASSIM.                           #\n");
    printf("#                                       #\n");
    printf("#########################################\n");
    printf("\n");
    printf("\n");
    printf("#################################################################################\n");
    printf("#                         exemplo                                               #\n");
    printf("#                                                                               #\n");
    printf("#  PORTUGUES --  N1 = VALOR  N2 = VALOR N3 = VALOR N4 = VALOR                   #\n");
    printf("#  PORTUGUES -- MD = MEDIA FINAL                                                #\n");
    printf("#                                                                               #\n");
    printf("#  NOTAS QUE TIVEREM '*' SIGINIFICA QUE E A NOTA NECESSARIA PARA PASSAR DE ANO  #\n");
    printf("#                                                                               #\n");
    printf("#################################################################################\n");
    printf("\n");
    printf("\n");
    printf(" ARTE -- N1 = 58 | N2 = 70 | N3 = 65 | N4 = 89 | \n");
    int arte_n1, arte_n2, arte_n3, arte_n4, media;
    arte_n1 = 58; 
    arte_n2 = 70; 
    arte_n3 = 65; 
    arte_n4 = 89;
    media = (arte_n1 + arte_n2 + arte_n3 + arte_n4 ) /4;
    printf(" ARTE -- MD %d | APROVADO <<--", media);
    printf("\n");
    printf("\n");
    printf(" BIOLOGIA -- N1 = 83 | N2 = 70 | N3 = 92 | N4 = 70* | \n");
    int biolo_n1, biolo_n2, biolo_n3, biolo_n4, biolo_media;
    biolo_n1 = 83;
    biolo_n2 = 70;
    biolo_n3 = 92;
    biolo_n4 = 70;
    biolo_media = (biolo_n1 + biolo_n2 + biolo_n3 + biolo_n4) /4;
    printf(" BIOLOGIA -- MD %d | APROVADO *", biolo_media);
    printf("\n");
    printf("\n");
    printf(" CONSTRUCAO DE ESTRADAS -- N1 = 70 | N2 = 90 | N3 = 55 | N4 = 70* | \n");
    int c_estradas_n1, c_estradas_n2, c_estradas_n3, c_estradas_n4, c_estradas_media;
    c_estradas_n1 = 70;
    c_estradas_n2 = 90;
    c_estradas_n3 = 55;
    c_estradas_n4 = 70;
    c_estradas_media = (c_estradas_n1 + c_estradas_n2 + c_estradas_n3 + c_estradas_n4) /4;
    printf(" C.ESTRADAS -- MD %d | APROVADO *", c_estradas_media);
    printf("\n");
    printf("\n");
    printf(" DRENAGEM -- N1 = 78 | N2 = 92 | N3 = 70* | N4 = 70* | \n");
    int drenagem_n1, drenagem_n2, drenagem_n3, drenagem_n4, drenagem_media;
    drenagem_n1 = 78;
    drenagem_n2 = 92;
    drenagem_n3 = 70;
    drenagem_n4 = 70;
    drenagem_media = (drenagem_n1 + drenagem_n2 + drenagem_n3 + drenagem_n4) /4;
    printf(" DRENAGEM -- MD %d | APROVADO *", drenagem_media);
    printf("\n");
    printf("\n");
    printf(" ED.FISICA -- N1 = 70 | N2 = 95 | N3 = 70 | N4 = 70* | \n");
    int ed_fisica_n1, ed_fisica_n2, ed_fisica_n3, ed_fisica_n4, ed_fisica_media;
    ed_fisica_n1 = 70;
    ed_fisica_n2 = 95;
    ed_fisica_n3 = 70;
    ed_fisica_n4 = 70;
    ed_fisica_media = (ed_fisica_n1 + ed_fisica_n2 + ed_fisica_n3 + ed_fisica_n4) /4;
    printf(" ED.FISICA -- MD %d | APROVADO *", ed_fisica_media);
    printf("\n");
    printf("\n");
    printf(" E.GEOMETRICO -- N1 = 100 | N2 = 85 | N3 = 70 | N4 = 70* | \n");
    int e_geometrico_n1, e_geometrico_n2, e_geometrico_n3, e_geometrico_n4, e_geometrico_media;
    e_geometrico_n1 = 100;
    e_geometrico_n2 = 85;
    e_geometrico_n3 = 70; 
    e_geometrico_n4 = 70;
    e_geometrico_media = (e_geometrico_n1 + e_geometrico_n2 + e_geometrico_n3 + e_geometrico_n4) /4;
    printf(" E.GEOMETRICO -- MD %d | APROVADO *", e_geometrico_media);
    printf("\n");
    printf("\n");
    printf(" EMPREENDEDORISMO -- N1 = 90 | N2 = 70 | N3 = 70* | N4 = 70* | \n");
    int empre_n1, empre_n2, empre_n3, empre_n4, empre_media;
    empre_n1 = 90;
    empre_n2 = 70;
    empre_n3 = 70;
    empre_n4 = 70;
    empre_media = (empre_n1 + empre_n2 + empre_n3 + empre_n4) /4;
    printf(" EMPREENDEDORISMO -- MD %d | APROVADO *", empre_media);
    printf("\n");
    printf("\n");
    printf(" E.MEIO AMBIENTE -- N1 = 84 | N2 = 90 | N3 = 45 | N4 = 70* | \n");
    int meio_ambiente_n1, meio_ambiente_n2, meio_ambiente_n3, meio_ambiente_n4, meio_ambiente_media;
    meio_ambiente_n1 = 84;
    meio_ambiente_n2 = 90;
    meio_ambiente_n3 = 45;
    meio_ambiente_n4 = 70;
    meio_ambiente_media = (meio_ambiente_n1 + meio_ambiente_n2 + meio_ambiente_n3 + meio_ambiente_n4) /4;
    printf(" ESTRADAS E MEIO AMBIENTE -- MD %d | APROVADO *", meio_ambiente_media);
    printf("\n");
    printf("\n");
    printf(" FILOSOFIA -- N1 = 82 | N2 = 90 | N3 = 82 | N4 = 90 | \n");
    int filo_n1, filo_n2, filo_n3, filo_n4, filo_media;
    filo_n1 = 82;
    filo_n2 = 90; 
    filo_n3 = 82;
    filo_n4 = 90;
    filo_media = (filo_n1 + filo_n2 + filo_n3 + filo_n4) / 4;
    printf(" FILOSOFIA -- MD %d | APROVADO ", filo_media);
    printf("\n");
    printf("\n");
    printf(" FISICA -- N1 = 82 | N2 = 78 | N3 = 75 | N4 = 70* | \n");
    int fisica_n1, fisica_n2, fisica_n3, fisica_n4, fisica_media;
    fisica_n1 = 85;
    fisica_n2 = 78;
    fisica_n3 = 75;
    fisica_n4 = 70;
    fisica_media = (fisica_n1 + fisica_n2 + fisica_n3 + fisica_n4) /4;
    printf(" FISICA -- MD %d | APROVADO ", fisica_media);
    printf("\n");
    printf("\n");
    printf(" GEOGRAFIA -- N1 = 100 | N2 = 88 | N3 = 95 | N4 = 70* | \n");
    int geo_n1, geo_n2, geo_n3, geo_n4, geo_media;
    geo_n1 = 100;
    geo_n2 = 88;
    geo_n3 = 95;
    geo_n4 = 70;
    geo_media = (geo_n1 + geo_n2 + geo_n3 + geo_n4) /4;
    printf(" GEOGRAFIA -- MD %d | APROVADO *", geo_media);
    printf("\n");
    printf("\n");
    printf(" GEOLOGIA -- N1 = 60 | N2 = 80 | N3 = 55 | N4 = 90* | \n");
    int geolo_n1, geolo_n2, geolo_n3, geolo_n4, geolo_media;
    geolo_n1 = 0;
    geolo_n2 = 80;
    geolo_n3 = 55;
    geolo_n4 = 90;
    geolo_media = (geolo_n1 + geolo_n2 + geolo_n3 + geolo_n4) /4;
    printf(" GEOLOGIA -- MD %d | CURSANDO ", geolo_media);
    printf("\n");
    printf("\n");
    printf(" HISTORIA -- N1 = 0 | N2 = 92 | N3 = 94 | N4 = 95* | \n");
    int his_n1, his_n2, his_n3, his_n4, his_media;
    his_n1 = 0;
    his_n2 = 92;
    his_n3 = 94;
    his_n4 = 95;
    his_media = (his_n1 + his_n2 + his_n3 + his_n4) /4;
    printf(" HISTORIA -- MD %d | CURSANDO ", his_media);
    printf("\n");
    printf("\n");
    printf(" L.PORTUGUES -- N1 = 70 | N2 = 88 | N3 = 79 | N4 = 70* | \n");
    int portu_n1, portu_n2, portu_n3, portu_n4, portu_media;
    portu_n1 = 70;
    portu_n2 = 88;
    portu_n3 = 79;
    portu_n4 = 70;
    portu_media = (portu_n1 + portu_n2 + portu_n3, portu_n4) /4;
    printf(" L.PORTUGUESA -- MD %d | CURSANDO ", portu_media);
    printf("\n");
    printf("\n");
    printf(" MATEMATICA -- N1 = 70 | N2 = 72 | N3 = 75 | N4 = 65 | \n");
    int mat_n1, mat_n2, mat_n3, mat_n4, mat_media;
    mat_n1 = 70;
    mat_n2 = 72;
    mat_n3 = 75;
    mat_n4 = 65;
    mat_media = (mat_n1 + mat_n2 + mat_n3 + mat_n4) /4;
    printf(" MATEMATICA -- MD %d | APROVADO <<-- ", mat_media);
    printf("\n");
    printf("\n");
    printf(" QUIMICA -- N1 = 70 | N2 = 72 | N3 = 70 | N4 = 70* | \n");
    int qui_n1, qui_n2, qui_n3, qui_n4, qui_media;
    qui_n1 = 70;
    qui_n2 = 72;
    qui_n3 = 70;
    qui_n4 = 70;
    qui_media = (qui_n1 + qui_n2 + qui_n3 + qui_n4) /4;
    printf(" QUIMICA -- MD %d | CURSANDO ", qui_media);
    printf("\n");
    printf("\n");
    printf(" S. TRANSPORTE -- N1 = 100 | N2 = 100 | N3 = 85 | N4 = 0 | \n");
    int trans_n1, trans_n2, trans_n3, trans_n4, trans_media;
    trans_n1 = 100;
    trans_n2 = 100;
    trans_n3 = 85;
    trans_n4 = 0;
    trans_media = (trans_n1 + trans_n2 + trans_n3 + trans_n4) /4;
    printf(" S. TRANSPORTE -- MD %d | CURSANDO <<-- ", trans_media);
    printf("\n");
    printf("\n");
    printf(" SOCIOLOGIA -- N1 = 28 | N2 = 90* | N3 = 28 | N4 = 90* | \n");
    int socio_n1, socio_n2, socio_n3, socio_n4, socio_media;
    socio_n1 = 28;
    socio_n2 = 90;
    socio_n3 = 28;
    socio_n4 = 90;
    socio_media = (socio_n1 + socio_n2 + socio_n3 + socio_n4) /4;
    printf(" SOCIOLOGIA -- MD %d | CURSANDO ", socio_media);
    return;
}

